src/AppBundle/Resources/views/Extensions/validation-policy.html.twig
=> Anchor highlighting for extension validation policies

src/AppBundle/Resources/views/Extensions/writing.html.twig
=> extension writing - permissions

src/AppBundle/Resources/views/Extensions/validation-policy.html.twig
=> Clarify validation policy on event prefixing

src/AppBundle/Resources/views/Extensions/epv.html.twig
=> EPV display updates

src/AppBundle/Controller/ExtensionsController.php
=> Update Auto Groups contribution link

app/Resources/views/base/javascript.html.twig, src/AppBundle/Resources/views/About/features.html.twig
It's not necessary so I removed it
=> replaced qtip with html

src/AppBundle/Twig/GlobalsExtension.php
=> Prep 3.1.5 release

src/AppBundle/Resources/views/Extensions/validation-policy.html.twig
=> Update extension validation policy

src/AppBundle/Twig/GlobalsExtension.php
=> Release 3.1.6

src/AppBundle/Controller/ExtensionsController.php
=> Add Collapsible Categories to Official Extensions page

src/AppBundle/Twig/GlobalsExtension.php
=> Release phpBB 3.1.8

src/AppBundle/Twig/GlobalsExtension.php
Reverts phpbb/phpbb-website#87
=> Revert "Release phpBB 3.1.10"

src/AppBundle/Twig/GlobalsExtension.php
Reverts phpbb/phpbb-website#89
=> Revert "Revert "Release phpBB 3.1.10""

app/config/parameters_tests.dist.yml, app/config/parameters_travis.yml, src/AppBundle/Controller/VigLinkController.php, src/AppBundle/Resources/config/routing.yml, src/AppBundle/Tests/Controller/VigLinkControllertest.php
=> Updated VigLink implementation

app/Resources/views/base/base.html.twig
I thought I only had 11 days left to live. This fixes that for countless other users who must be having the same issue as me.
This is a _yolo fix_, please test before merging.
=> Made countdown timer less spooky 👻

src/AppBundle/Wrappers/PhpbbHandling.php
Reverts phpbb/phpbb-website#104
Currently results in an error being thrown on .com. Unsure what the issue is without a proper error log.
=> Revert "Use new s9e text formatter way of stripping bbcodes"

src/AppBundle/Resources/views/Development/gsoc_ideas.html.twig
=> Add myself to the mentors list for the convertor idea

src/AppBundle/Resources/views/About/contact.html.twig
File modified - src/AppBundle/Resources/views/About/contact.html.twig
To implement the changes
1312
=> [ticket/1312] Typo - "its", not "it's"

src/AppBundle/Controller/ExtensionsController.php
Requires https://github.com/phpbb/website-assets/pull/12
=> Add Media Embed to Official Extensions

src/AppBundle/Twig/GlobalsExtension.php
https://github.com/phpbb/website/pull/150
=> Update GlobalsExtensions.php for 3.2.1 release

composer.lock
Update assets version to fix issue with PM display on mobile devices
=> Update assets version for fixing PM CSS

app/Resources/views/base/base.html.twig
Inserted site name and bullet before the title block in the base template.
=> WEBSITE-1291 - some page titles aren't suitable for bookmarking.

src/AppBundle/Twig/GlobalsExtension.php
Change landing pages in navigation bar links from 3.1 to 3.2 following 3.1's EOM.
=> Change KB and Documentation landing pages

src/AppBundle/Twig/GlobalsExtension.php
<a href="https://tracker.phpbb.com/browse/WEBSITE-1338">WEBSITE-1338</a>.
=> [ticket/1338] Fix extensions dev tutorial links

src/AppBundle/Resources/views/Development/gsoc_ideas.html.twig
Changes and additions to our Google Summer of Code 2018 pages.
=> Add additional GSoC 2018 ideas

src/AppBundle/Resources/views/Development/gsoc.html.twig
=> Add Senky to mentors list for GSoC 2018

src/AppBundle/Resources/views/Development/gsoc_ideas.html.twig
Propose that we be more specific and to the point to avoid the rabbit holes we went down last year with this.
=> Update AdminUI idea with more details

src/AppBundle/Resources/views/Support/intl.html.twig
=> Add a new italian support page to the INTL list

src/AppBundle/Resources/views/About/getInvolved.html.twig
https://www.phpbb.com/community/viewtopic.php?f=556&t=2473686
=> Fix wrong link to the bugtracker.
